@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=D:\guesthouse_app\react_frontend\my-react-web-app\New Testing Exe.exe
REM BFCPEICON=
REM BFCPEICONINDEX=-1
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=0
REM BFCPEINVISEXE=0
REM BFCPEVERINCLUDE=1
REM BFCPEVERVERSION=1.0.0.0
REM BFCPEVERPRODUCT=LodgeControl
REM BFCPEVERDESC=Guest House Managment System
REM BFCPEVERCOMPANY=Aarkay's Solutions
REM BFCPEVERCOPYRIGHT=Aarkay's Solutions Auguest 2025
REM BFCPEWINDOWCENTER=1
REM BFCPEDISABLEQE=0
REM BFCPEWINDOWHEIGHT=30
REM BFCPEWINDOWWIDTH=120
REM BFCPEWTITLE=Window Title
REM BFCPEOPTIONEND
@echo off
echo Launching your app...
node "%~dp0launcher.js"
echo.
echo App finished. Press any key to close.
pause
