name: Deploy Frontend to Railway

on:
  push:
    paths:
      - "react_frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v2
        with:
          serviceId: ${{ secrets.RAILWAY_FRONTEND_SERVICE_ID }}
          token: ${{ secrets.RAILWAY_API_TOKEN }}
